-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 09:44:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET
  @OLD_UNIQUE_CHECKS = @ @UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;

SET
  @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;

SET
  @OLD_SQL_MODE = @ @SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;

USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `picture` BLOB NULL,
  `pseudo` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `hashedpassword` VARCHAR(255) NOT NULL,
  `workplace` VARCHAR(255) NULL,
  `github` VARCHAR(255) NULL,
  `linkedin` VARCHAR(255) NULL,
  `language` VARCHAR(255) NOT NULL,
  `user_text` LONGTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`language` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `language_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_creation_date` DATE GENERATED ALWAYS AS ("YYYY-MM-DD") VIRTUAL,
  `tag` VARCHAR(255) NOT NULL,
  `post_text` LONGTEXT NOT NULL,
  `language_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `language_id`, `user_id`),
  INDEX `fk_post_language1_idx` (`language_id` ASC) VISIBLE,
  INDEX `fk_post_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_language1` FOREIGN KEY (`language_id`) REFERENCES `mydb`.`language` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user1` FOREIGN KEY (`user_id`) REFERENCES `mydb`.`user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer_creation_date` DATE GENERATED ALWAYS AS ("YYYY-MM-DD") VIRTUAL,
  `answer_text` LONGTEXT NOT NULL,
  `post_id` INT NOT NULL,
  `post_language_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `post_id`, `post_language_id`, `user_id`),
  INDEX `fk_answer_post1_idx` (`post_id` ASC, `post_language_id` ASC) VISIBLE,
  INDEX `fk_answer_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_post1` FOREIGN KEY (`post_id`, `post_language_id`) REFERENCES `mydb`.`post` (`id`, `language_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_user1` FOREIGN KEY (`user_id`) REFERENCES `mydb`.`user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`user_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_language` (
  `user_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `language_id`),
  INDEX `fk_user_has_language_language1_idx` (`language_id` ASC) VISIBLE,
  INDEX `fk_user_has_language_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_language_user1` FOREIGN KEY (`user_id`) REFERENCES `mydb`.`user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_language_language1` FOREIGN KEY (`language_id`) REFERENCES `mydb`.`language` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET
  SQL_MODE = @OLD_SQL_MODE;

SET
  FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET
  UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;